#ifndef HFDL_RATIONAL_RESAMPLER_H
#define HFDL_RATIONAL_RESAMPLER_H

#include <stdint.h>
#include "arm_math.h"

/*
 * HFDL 12000Hz -> 5400Hz rational resampler (interpolate by 9, decimate
 * by 20 - a FIXED, exactly-known ratio, unlike dumphfdl's arbitrary-rate
 * msresamp_crcf, which our native 12kHz audio doesn't need). Feeds
 * hfdl_symsync.c's k=3 input (5400Hz = 1800baud * 3 samples/symbol).
 *
 * This module was added after a mid-session course correction: an
 * earlier plan (Farrow interpolator + Gardner TED, no resampler stage
 * at all) was replaced with porting dumphfdl's REAL symsync algorithm
 * once its actual coefficient cost turned out to be modest (~1-2KB,
 * not the large cost originally assumed) - see the project's session
 * notes. Porting the real symsync means also needing the fixed-ratio
 * resampler it depends on - this module.
 *
 * Algorithm: classic polyphase rational resampler, replicated line-by-
 * line from liquid-dsp's rresamp_crcf_create_kaiser() +
 * rresamp_crcf_execute_primitive() (jgaeddert/liquid-dsp, MIT) - NOT
 * reimplemented from a description, the actual source was read and
 * followed exactly, including a detail worth flagging: liquid's own
 * firpfb_create() does h_sub_len = h_len/num_filters using INTEGER
 * division, which silently drops 1 coefficient (145 -> 144 used) for
 * these exact parameters - this is liquid-dsp's own real behavior,
 * confirmed present in the reference implementation itself, not
 * something introduced or "fixed" here.
 *
 * Design parameters (this project's own choice, NOT dumphfdl's - dumphfdl
 * never needed a fixed-ratio resampler): m=8 (filter delay), as=60dB
 * (stopband attenuation), bw=auto (critical bandwidth for this
 * interp<decim case = 0.5*9/20 = 0.225). Coefficients generated by
 * actually compiling and running liquid-dsp's real
 * liquid_firdes_kaiser() in this project's development environment,
 * not hand-derived - see the project's session notes for the generator
 * source and raw output.
 *
 * hfdl_resamp_pfb[][]: the resulting 9-phase, 16-tap-per-phase
 * polyphase filterbank, ALREADY time-reversed per firpfb_create()'s
 * own convention - a plain forward dot-product against a
 * chronologically-ordered history buffer (oldest-to-newest) reproduces
 * liquid's FIRPFB(_execute)() exactly. See hfdl_rational_resampler.c.
 *
 * OUTPUT SCALE: liquid's rresamp_crcf_create_kaiser() additionally
 * calls RRESAMP(_set_scale)() with scale = 2*bw_eff*sqrt(Q/P) - this
 * module applies that same scale factor (see
 * HFDL_RESAMP_OUTPUT_SCALE below) so output amplitude conventions
 * match what a real liquid-dsp rresamp_crcf object would produce.
 */

#define HFDL_RESAMP_NUM_PHASES     9   /* P: interpolation factor */
#define HFDL_RESAMP_DECIM          20  /* Q: decimation factor - HFDL_RESAMP_NUM_PHASES/HFDL_RESAMP_DECIM = 9/20 = 12000Hz -> 5400Hz */
#define HFDL_RESAMP_SUBFILTER_LEN  16  /* taps per polyphase phase */

/* = 2*0.225*sqrt(20/9), computed the same way liquid's rresamp_crcf_create_kaiser()
 * computes its internal output scale factor for these exact parameters. */
#define HFDL_RESAMP_OUTPUT_SCALE 0.6708203932499369f

extern const float32_t hfdl_resamp_pfb[HFDL_RESAMP_NUM_PHASES][HFDL_RESAMP_SUBFILTER_LEN];

typedef struct {
	/* Chronologically-ordered (oldest-to-newest) history of the last
	 * HFDL_RESAMP_SUBFILTER_LEN input samples, shared across all 9
	 * phases - mirrors liquid's single shared WINDOW inside firpfb. */
	float32_t hist_i[HFDL_RESAMP_SUBFILTER_LEN];
	float32_t hist_q[HFDL_RESAMP_SUBFILTER_LEN];
} hfdl_rational_resampler_t;

/* Clears history to zero (call once at init, or again to reset state
 * e.g. at the start of a new HFDL burst). */
void hfdl_rational_resampler_init(hfdl_rational_resampler_t *r);

/* Processes exactly HFDL_RESAMP_DECIM (20) input I/Q samples and
 * writes exactly HFDL_RESAMP_NUM_PHASES (9) output I/Q samples -
 * mirrors liquid's rresamp_crcf_execute_primitive() one-to-one,
 * including its internal filterbank-index bookkeeping. Caller must
 * supply exactly 20 input samples and provide room for exactly 9
 * output samples - this module does not buffer partial blocks
 * internally (matches liquid's own _execute(), which has the same
 * fixed-block-size contract; a later integration step, once this
 * feeds into the real 12kHz pipeline, will need to handle
 * accumulating audio into 20-sample chunks - not yet done, this
 * module is self-contained and independently testable first). */
void hfdl_rational_resampler_process(hfdl_rational_resampler_t *r,
		const float32_t *i_in, const float32_t *q_in,
		float32_t *i_out, float32_t *q_out);

/* Runs the module's standalone self-test:
 *   1) DC gain check - a constant input, once history has fully
 *      filled (past the initial transient), should produce a constant
 *      output whose value matches the filter's computed DC gain
 *      (sum of the phase-0 tap set, scaled by HFDL_RESAMP_OUTPUT_SCALE)
 *      to a tight tolerance.
 *   2) Structural check that hfdl_resamp_pfb[phase 0] contains the
 *      expected unity-ish peak near its center tap (a real windowed-
 *      sinc lowpass property, sanity-checks the generated table wasn't
 *      corrupted/mistyped).
 * Zero dependency on real hardware or a real HFDL signal - like the
 * other DSP-block self-tests, this proves the resampler mechanics
 * are correct, not that m=8/as=60dB were definitely the ideal design
 * choice (that's this project's own design decision, not something
 * dumphfdl specifies - see the module header). */
uint8_t hfdl_rational_resampler_selftest(void);

#endif /* HFDL_RATIONAL_RESAMPLER_H */
